<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.0.0</Version>
    <RuntimeIdentifiers>win-x64;linux-x64;osx-x64</RuntimeIdentifiers>
    <Authors>Daniel Klecha</Authors>
    <Copyright>Daniel Klecha</Copyright>
    <Description>IPP printer</Description>
    <StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>
    <RestoreLockedMode>false</RestoreLockedMode>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="jobs\**" />
    <Content Remove="jobs\**" />
    <EmbeddedResource Remove="jobs\**" />
    <None Remove="jobs\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Makaretu.Dns.Multicast" />
    <PackageReference Include="SharpIppNext" />
    <PackageReference Include="System.IO.Abstractions" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\THIRD-PARTY-NOTICES.txt">
      <Link>THIRD-PARTY-NOTICES.txt</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\LICENSE.txt">
      <Link>LICENSE.txt</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
