name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish win-x64
      run: dotnet publish --no-restore --configuration Release --runtime win-x64 --no-self-contained
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Copy license win-x64
      run: |
        cp LICENSE.txt SharpIppNextServer/bin/Release/net8.0/win-x64/publish/LICENSE.txt
    - name: Install zip
      uses: montudor/action-zip@v1
    - name: Pack win-x64
      run: zip -qq -r "../../../SharpIppNextServer-${{github.ref_name}}-win-x64.zip" *.*
      working-directory: SharpIppNextServer/bin/Release/net8.0/win-x64/publish/
    - name: Publish linux-x64
      run: dotnet publish --no-restore --configuration Release --runtime linux-x64 --no-self-contained
    - name: Copy license linux-x64
      run: |
        cp LICENSE.txt SharpIppNextServer/bin/Release/net8.0/linux-x64/publish/LICENSE.txt
    - name: Pack linux-x64
      run: zip -qq -r ../../../SharpIppNextServer-${{github.ref_name}}-linux-x64.zip *.*
      working-directory: SharpIppNextServer/bin/Release/net8.0/linux-x64/publish/
    - name: Publish osx-x64
      run: dotnet publish --no-restore --configuration Release --runtime osx-x64 --no-self-contained
    - name: Copy license osx-x64
      run: |
        cp LICENSE.txt SharpIppNextServer/bin/Release/net8.0/osx-x64/publish/LICENSE.txt
    - name: Pack osx-x64
      run: zip -qq -r ../../../SharpIppNextServer-${{github.ref_name}}-osx-x64.zip *.*
      working-directory: SharpIppNextServer/bin/Release/net8.0/osx-x64/publish/
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "SharpIppNextServer/bin/Release/*.zip"
        bodyFile: "RELEASE.md"
